/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function BarWoodenFloor(props) {
  const { nodes, materials } = useGLTF("/bar/floor.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Floor_1.geometry}
        material={materials["Wood Floor"]}
      />
    </group>
  );
}

useGLTF.preload("/bar/floor.glb");
