/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Barrel(props) {
  const { nodes, materials } = useGLTF("/bar/barrel.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Barrel.geometry}
        material={materials.TableWood}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Barrel_1.geometry}
        material={materials.Metal}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Barrel_2.geometry}
        material={materials["Barrel lid"]}
      />
    </group>
  );
}

useGLTF.preload("/bar/barrel.glb");
