/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Chicken(props) {
  const { nodes, materials } = useGLTF("/bar/chicken.glb");
  return (
    <group {...props} dispose={null}>
      <group scale={0.916}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Chicken_2.geometry}
          material={materials.Bone}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Chicken_3.geometry}
          material={materials.Chicken}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/bar/chicken.glb");
