/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function EmptyMug(props) {
  const { nodes, materials } = useGLTF("/bar/empty_mug.glb");
  return (
    <group {...props} dispose={null}>
      <group rotation={[0, 0.411, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mug_2.geometry}
          material={materials.Metal}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mug_2_1.geometry}
          material={materials["Column wood"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mug_2_2.geometry}
          material={nodes.mug_2_2.material}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/bar/empty_mug.glb");
