/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Mug(props) {
  const { nodes, materials } = useGLTF("/bar/mug.glb");
  return (
    <group {...props} dispose={null}>
      <group rotation={[0, 0.505, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mug_1_2.geometry}
          material={materials["Column wood"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mug_1_3.geometry}
          material={materials.Metal}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mug_1_4.geometry}
          material={materials.Froth}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/bar/mug.glb");
