/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Plate(props) {
  const { nodes, materials } = useGLTF("/bar/plate.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plate_Wood_1.geometry}
        material={materials["Column wood"]}
      />
    </group>
  );
}

useGLTF.preload("/bar/plate.glb");
