/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Shield(props) {
  const { nodes, materials } = useGLTF("/bar/shield.glb");
  return (
    <group {...props} dispose={null}>
      <group rotation={[Math.PI / 2, -Math.PI / 2, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane.geometry}
          material={materials.Metal}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane_1.geometry}
          material={materials["Column wood"]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/bar/shield.glb");
