/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Sword(props) {
  const { nodes, materials } = useGLTF("/bar/sword.glb");
  return (
    <group {...props} dispose={null}>
      <group rotation={[-1.515, -0.219, 2.669]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder008.geometry}
          material={materials.Metal}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder008_1.geometry}
          material={materials["Barrel lid"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder008_2.geometry}
          material={materials["Chest corners"]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/bar/sword.glb");
