/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Table(props) {
  const { nodes, materials } = useGLTF("/bar/table.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Table_1.geometry}
        material={materials.TableWood}
      />
    </group>
  );
}

useGLTF.preload("/bar/table.glb");
