/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Torch(props) {
  const { nodes, materials } = useGLTF("/bar/torch.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Torch_1.geometry}
        material={materials.Metal}
      >
        <pointLight
          intensity={5}
          decay={2}
          distance={10}
          color="#fdaa49"
          position={[5.245, 4.307, -7.141]}
          rotation={[Math.PI, 0, Math.PI]}
        />
      </mesh>
    </group>
  );
}

useGLTF.preload("/bar/torch.glb");
