/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Arrow(props) {
  const { nodes, materials } = useGLTF("/arrow.glb");

  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.arrow_2.geometry}
        position={[0, 0, 0]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={4}
      >
        <meshStandardMaterial
          map={materials["atlas_Built-in"].map}
          color="#ffffff"
          emissive="#ffff00" // Yellow glow
          emissiveIntensity={0.5} // Brightness boost
          toneMapped={false} // Bypass tone mapping for extra brightness
        />
      </mesh>
    </group>
  );
}

useGLTF.preload("/arrow.glb");
