/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from "@react-three/drei";
import { RigidBody } from "@react-three/rapier";

export const BertHouse = (props: any) => {
  const { nodes, materials } = useGLTF("/bert_house.glb");
  return (
    <RigidBody
      type="fixed"
      colliders={"trimesh"}
      position={[-36.347, -0.29, 12.241]}
      scale={[1.5, 1.5, 2]}
      rotation={[-0.01, Math.PI / 2 - 0.3, 0]}
      {...props}
    >
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube.geometry}
        material={materials["Int Walls"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube_1.geometry}
        material={materials.Name}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube_2.geometry}
        material={materials.Roof}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube_3.geometry}
        material={materials["Ext Walls"]}
      />
    </RigidBody>
  );
};

useGLTF.preload("/bert_house.glb");
