/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Cake(props) {
  const { nodes, materials } = useGLTF("/cake.glb");
  materials["atlas_Built-in"].emissiveIntensity = 0.8;
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.cake_2.geometry}
        material={materials["atlas_Built-in"]}
        position={[0.016, 0, -0.015]}
        scale={1.46}
      />
    </group>
  );
}

useGLTF.preload("/cake.glb");
