/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react';
import { Instance, Instances, useGLTF } from '@react-three/drei';
import type { Mesh } from 'three';

export function Flower01(props: any) {
  const { nodes, materials } = useGLTF('/flower_01.glb');
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={(nodes.rpgpp_lt_flower_01_1 as any).geometry}
        material={materials.rpgpp_lt_mat_a}
      />
    </group>
  );
}


export function Flower02(props: any) {
  const { nodes, materials } = useGLTF('/flower_02.glb');
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={(nodes.rpgpp_lt_flower_02_1 as any).geometry}
        material={materials.rpgpp_lt_mat_a}
      />
    </group>
  );
}


export function Flower03(props: any) {
  const { nodes, materials } = useGLTF('/flower_03.glb');
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={(nodes.rpgpp_lt_flower_03_1 as any).geometry}
        material={materials.rpgpp_lt_mat_a}
      />
    </group>
  );
}


interface LocationData {
  position: [number, number, number];
  rotation: [number, number, number];
}
export const Flowers = () => {
  const { nodes: nodes1, materials } = useGLTF('/flower_01.glb');
  const { nodes: nodes2 } = useGLTF('/flower_02.glb');
  const { nodes: nodes3 } = useGLTF('/flower_03.glb');

  // Fixed positions and rotations for each flower type
  const flower1Data: Array<LocationData> = [
    { position: [-25, 0, -15], rotation: [0, 0, 0] },
    { position: [-18, 0, 8], rotation: [0, 1.57, 0] },
    { position: [-12, 0, -28], rotation: [0, 3.14, 0] },
    { position: [-5, 0, 12], rotation: [0, 4.71, 0] },
    { position: [3, 0, -8], rotation: [0, 0.78, 0] },
    { position: [10, 0, 22], rotation: [0, 2.35, 0] },
    { position: [18, 0, -18], rotation: [0, 3.92, 0] },
    { position: [25, 0, 5], rotation: [0, 5.49, 0] },
    { position: [-22, 0, 25], rotation: [0, 1.04, 0] },
    { position: [15, 0, -25], rotation: [0, 2.61, 0] },
  ];

  const flower2Data: Array<LocationData> = [
    { position: [-28, 0, -5], rotation: [0, 0.52, 0] },
    { position: [-15, 0, 18], rotation: [0, 1.83, 0] },
    { position: [-8, 0, -24], rotation: [0, 3.4, 0] },
    { position: [0, 0, 15], rotation: [0, 4.97, 0] },
    { position: [8, 0, -12], rotation: [0, 0.26, 0] },
    { position: [15, 0, 28], rotation: [0, 1.31, 0] },
    { position: [22, 0, -8], rotation: [0, 2.88, 0] },
    { position: [28, 0, 18], rotation: [0, 4.45, 0] },
    { position: [-20, 0, -28], rotation: [0, 5.76, 0] },
    { position: [12, 0, 8], rotation: [0, 1.05, 0] },
  ];

  const flower3Data: Array<LocationData> = [
    { position: [-30, 0, 10], rotation: [0, 1.3, 0] },
    { position: [-12, 0, -5], rotation: [0, 2.87, 0] },
    { position: [-3, 0, 25], rotation: [0, 4.44, 0] },
    { position: [5, 0, -17], rotation: [0, 0.65, 0] },
    { position: [12, 0, 18], rotation: [0, 2.22, 0] },
    { position: [20, 0, -25], rotation: [0, 3.79, 0] },
    { position: [28, 0, 8], rotation: [0, 5.36, 0] },
    { position: [-25, 0, -22], rotation: [0, 0.91, 0] },
    { position: [-8, 0, 28], rotation: [0, 2.48, 0] },
    { position: [25, 0, -12], rotation: [0, 4.05, 0] },
  ];

  return (
    <>
      {/* Flower 01 instances */}
      <Instances
        range={flower1Data.length}
        geometry={(nodes1.rpgpp_lt_flower_01_1 as Mesh).geometry}
        material={materials.rpgpp_lt_mat_a}
      >
        {flower1Data.map((data, index) => (
          <Instance
            key={`flower1-${index}`}
            position={data.position}
            rotation={data.rotation}
          />
        ))}
      </Instances>

      {/* Flower 02 instances */}
      <Instances
        range={flower2Data.length}
        geometry={(nodes2.rpgpp_lt_flower_03_1 as Mesh).geometry}
        material={materials.rpgpp_lt_mat_a}
      >
        {flower2Data.map((data, index) => (
          <Instance
            key={`flower2-${index}`}
            position={data.position}
            rotation={data.rotation}
          />
        ))}
      </Instances>

      {/* Flower 03 instances */}
      <Instances
        range={flower3Data.length}
        geometry={(nodes3.rpgpp_lt_flower_02_1 as Mesh).geometry}
        material={materials.rpgpp_lt_mat_a}
      >
        {flower3Data.map((data, index) => (
          <Instance
            key={`flower3-${index}`}
            position={data.position}
            rotation={data.rotation}
          />
        ))}
      </Instances>
    </>
  );
};
