/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Heart(props) {
  const { nodes, materials } = useGLTF("/heart.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.playing_cards_hearts_2.geometry}
        material={materials["atlas_Built-in"]}
        position={[0, 0, 0]}
      />
    </group>
  );
}

useGLTF.preload("/heart.glb");
