/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from "@react-three/drei";
import { CuboidCollider, RigidBody } from "@react-three/rapier";
import type { Mesh } from "three";

export const Horse = (props: any) => {
  const { nodes, materials } = useGLTF("/horse.glb");
  return (
    <RigidBody
      type="fixed"
      colliders={false}
      position={[25.347, -0.31, -0.241]}
      scale={2.5}
      rotation={[0, -Math.PI / 2, 0]}
      {...props}
    >
      <CuboidCollider args={[0.2, 1.6, 1]} />

      <mesh
        castShadow
        receiveShadow
        geometry={(nodes.horse as Mesh).geometry}
        material={materials.PaletteMaterial001}
      />
    </RigidBody>
  );
};

useGLTF.preload("/horse.glb");
