/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Horseshoe(props) {
  const { nodes, materials } = useGLTF("/horseshoe.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.horseshoe_2.geometry}
        material={materials["atlas_Built-in"]}
        position={[0, 0, -9.25]}
      />
    </group>
  );
}

useGLTF.preload("/horseshoe.glb");
