/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function IconCheck(props) {
  const { nodes, materials } = useGLTF("/icon_check.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.icon_check_2.geometry}
        material={materials["atlas_Built-in"]}
        position={[-1.875, 0, -9.75]}
      />
    </group>
  );
}

useGLTF.preload("/icon_check.glb");
