/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Kitty(props) {
  const { nodes, materials } = useGLTF("/kitty.glb");
  return (
    <group {...props} dispose={null}>
      <group position={[0, 0, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.cat_2.geometry}
          material={materials["atlas_Built-in"]}
          scale={10}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/kitty.glb");
