/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { Html, useGLTF } from "@react-three/drei";
import { RigidBody } from "@react-three/rapier";

export const Marshmallow = (props: any) => {
  const { nodes, materials } = useGLTF("/marshmallow.glb");

  materials.Bears.emissiveIntensity = 0.8;
  return (
    <group
      position={[-27.347, 1.15, -11.241]}
      scale={1.75}
      rotation={[0, 0.45, 0]}
      {...props}
      dispose={null}
    >
      <RigidBody type="fixed" colliders="cuboid">
        <mesh geometry={nodes.Cube.geometry} material={materials.Bears} />
      </RigidBody>

      <Html
        position={[0, 0.9, 0]}
        center
        zIndexRange={[30, 0]}
        distanceFactor={15}
      >
        <p className="text-black bg-white px-1 py-0.5 text-sm rounded-lg font-bold whitespace-nowrap hud">
          Marshmallow
        </p>
      </Html>
    </group>
  );
};

useGLTF.preload("/marshmallow.glb");
