/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Pumpkin(props: any) {
  const { nodes, materials } = useGLTF("/pumpkin.glb");
  materials.Material.emissiveIntensity = 0.5;
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.pumpkin.geometry}
        material={materials.Material}
      />
    </group>
  );
}

useGLTF.preload("/pumpkin.glb");
