/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Speaker(props) {
  const { nodes, materials } = useGLTF("/speaker.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Speaker_1.geometry}
        material={materials.Main}
        position={[0.37, 0.158, 34.4]}
      />
    </group>
  );
}

useGLTF.preload("/speaker.glb");
