/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from "@react-three/drei";
import { CuboidCollider, RigidBody } from "@react-three/rapier";

export const Village = (props: any) => {
  const { nodes, materials } = useGLTF("/village.glb", true);

  materials.Material.metalness = 0;
  materials.Material.roughness = 1;
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["hill_001_(3)"].geometry}
        material={materials.Material}
        position={[-119.6, 6.202, -18.05]}
        rotation={[-Math.PI, -1.475, -Math.PI]}
        scale={[1.916, 4.512, 1.916]}
      />

      {/* Table near the Blue Tavern */}
      <RigidBody
        type="fixed"
        colliders={false}
        position={[16, -0.25, 26]}
        rotation={[0, -0.114, -0.05]}
      >
        <CuboidCollider args={[2, 1.75, 1.75]} />
      </RigidBody>

      {/* Box near vegetables shop */}
      <RigidBody
        type="fixed"
        colliders={false}
        position={[9, -0.114, 25]}
        rotation={[0.06, -0.114, 0.006]}
      >
        <CuboidCollider args={[0.7, 1, 1]} />
      </RigidBody>

      {/* Three boxes near meat store */}
      <RigidBody
        type="fixed"
        colliders={false}
        position={[11, 1.117, 28]}
        rotation={[-0.004, -0.114, -0.001]}
      >
        <CuboidCollider args={[1, 1.25, 1]} />
      </RigidBody>

      {/* Long brown vase near meat store */}
      <RigidBody
        type="fixed"
        colliders={false}
        position={[7, -0.053, 34]}
        rotation={[-0.004, -0.114, -0.001]}
      >
        <CuboidCollider args={[0.25, 1.25, 0.25]} />
      </RigidBody>

      {/* Two vases near meat store */}
      <RigidBody
        type="fixed"
        position={[6.895, -0.004, 36.018]}
        rotation={[-0.004, -0.114, -0.001]}
        colliders={false}
      >
        <CuboidCollider args={[0.25, 1, 0.25]} />
      </RigidBody>

      {/* Table with cheese near meat store */}
      <RigidBody
        type="fixed"
        colliders={false}
        position={[9, 0.027, 38]}
        rotation={[-0.004, -0.114, -0.001]}
      >
        <CuboidCollider args={[1.5, 2.5, 1.25]} />
      </RigidBody>

      {/* Table with cheese near tomato store */}
      <RigidBody
        type="fixed"
        colliders={false}
        position={[-5, -0.11, 49]}
        rotation={[-0.004, -0.114, -0.001]}
      >
        <CuboidCollider args={[1.5, 2.5, 1.25]} />
      </RigidBody>

      {/* Tomato store */}
      <RigidBody
        type="fixed"
        position={[1, -0.13, 48]}
        rotation={[3.139, -0.639, 3.138]}
        colliders={false}
      >
        <CuboidCollider args={[2, 4, 2]} />
      </RigidBody>

      {/* Bonfire */}
      <RigidBody
        type="fixed"
        colliders={false}
        position={[-30, -0.42, 0]}
        rotation={[-0.004, -0.114, -0.001]}
        scale={1.583}
      >
        <CuboidCollider args={[0.5, 0.5, 0.5]} />
      </RigidBody>

      {/* Meat store */}
      <RigidBody
        type="fixed"
        colliders={false}
        position={[10, 0.069, 33]}
        rotation={[-3.139, -1.334, -3.135]}
      >
        <CuboidCollider args={[3, 4.3, 1.5]} />
      </RigidBody>

      {/* Vegetables store */}
      <RigidBody
        type="fixed"
        colliders={false}
        position={[12, -0.5, 21]}
        rotation={[0, -1.291, 0]}
      >
        <CuboidCollider args={[3.5, 5.5, 2]} />
      </RigidBody>

      {/* Box near the carpet and bonfire */}
      <RigidBody
        type="fixed"
        position={[-19, -0.287, 5]}
        rotation={[-3.138, -1.366, -3.134]}
        colliders={false}
      >
        <CuboidCollider args={[0.5, 1.25, 0.5]} />
      </RigidBody>

      {/* Water bucket near the bonfire */}
      <RigidBody
        type="fixed"
        position={[-23, -0.314, -5]}
        rotation={[-0.004, -0.114, -0.001]}
        colliders={false}
      >
        <CuboidCollider args={[0.25, 0.25, 0.25]} />
      </RigidBody>

      {/* Wagon */}
      <RigidBody
        type="fixed"
        colliders={false}
        position={[-5, -0.21, 25]}
        rotation={[-0.009, -1.282, -0.005]}
      >
        <CuboidCollider args={[1.5, 1.5, 2]} />
      </RigidBody>

      {/* Two brown vases near sliced meat store */}
      <RigidBody
        type="fixed"
        position={[-13, -0.041, 35]}
        rotation={[0.086, -0.124, -0.132]}
        colliders={false}
      >
        <CuboidCollider args={[0.25, 0.25, 0.25]} />
      </RigidBody>

      {/* Two small brown vases near sliced meat store */}
      <RigidBody
        type="fixed"
        position={[-12, -0.189, 34]}
        rotation={[0.007, -0.115, -0.036]}
        colliders={false}
      >
        <CuboidCollider args={[1, 0.5, 1]} />
      </RigidBody>

      {/* Pig on bonfire */}
      <RigidBody
        type="fixed"
        colliders={false}
        position={[-25, -0.26, -7]}
        rotation={[-0.001, 1.15, -0.004]}
      >
        <CuboidCollider args={[1, 1.5, 2]} />
      </RigidBody>

      {/* Sliced meat store near wagon */}
      <RigidBody
        type="fixed"
        colliders={false}
        position={[-3, -0.193, 31]}
        rotation={[0.008, 1.447, -0.012]}
      >
        <CuboidCollider args={[3, 5, 1.5]} />
      </RigidBody>

      {/* Well */}
      <RigidBody
        type="fixed"
        colliders={false}
        position={[-41, -0.394, 31]}
        rotation={[-0.006, -0.899, -0.002]}
      >
        <CuboidCollider args={[1.5, 5, 1.5]} />
      </RigidBody>

      {/* Spa Salon */}
      <RigidBody
        type="fixed"
        colliders={false}
        position={[34, -0.326, 41]}
        rotation={[-2.985, -1.456, -2.982]}
      >
        <CuboidCollider args={[4, 7, 5.5]} position={[0, 0, -0.25]} />
        <CuboidCollider
          args={[3.5, 0.15, 1.25]}
          position={[0, 4, 6.25]}
          rotation={[0.4, 0, 0]}
        />
      </RigidBody>

      {/* Blue Tavern */}
      <RigidBody
        type="fixed"
        colliders={false}
        position={[31, -0.26, 25]}
        rotation={[-0.007, -1.161, -0.004]}
      >
        <CuboidCollider args={[3.5, 11.5, 5.5]} />
        <CuboidCollider
          args={[2, 3, 4.5]}
          position={[-4, 8, -3]}
          rotation={[0, Math.PI / 2, 0]}
        />
      </RigidBody>

      {/* Right bench */}
      <RigidBody
        type="fixed"
        position={[-32, -0.52, -5]}
        rotation={[-0.003, 0.651, -0.002]}
        colliders={false}
      >
        <CuboidCollider args={[2, 1, 1]} />
      </RigidBody>

      {/* Center bench */}
      <RigidBody
        type="fixed"
        position={[-35, -0.42, -1]}
        rotation={[0.036, 1.534, -0.04]}
        colliders={false}
      >
        <CuboidCollider args={[2, 1, 1]} />
      </RigidBody>

      {/* Left bench */}
      <RigidBody
        type="fixed"
        position={[-32, -0.313, 4]}
        rotation={[3.137, 0.592, -3.14]}
        colliders={false}
      >
        <CuboidCollider args={[2, 1, 1]} />
      </RigidBody>

      {/* Golden tree in the center */}
      <RigidBody type="fixed" colliders={false} position={[-1, -0.291, 1]}>
        <CuboidCollider args={[1, 12.5, 1]} />
      </RigidBody>

      {/* Green tree on the right from the trampoline */}
      <RigidBody
        type="fixed"
        colliders={false}
        position={[35, -1.3, -6]}
        rotation={[Math.PI, -0.412, Math.PI]}
        scale={[0.92, 0.956, 1.123]}
      >
        <CuboidCollider args={[1, 7, 1]} />
      </RigidBody>

      {/* Golden tree near the well */}
      <RigidBody type="fixed" colliders={false} position={[-33, -0.119, 38]}>
        <CuboidCollider args={[0.75, 13.5, 0.75]} />
      </RigidBody>

      {/* First golden tree near Spa Salon */}
      <RigidBody
        type="fixed"
        colliders={false}
        position={[50, -0.58, 36]}
        rotation={[0, -1.021, 0]}
        scale={0.832}
      >
        <CuboidCollider args={[0.75, 10, 0.75]} />
      </RigidBody>

      {/* Green tree near the Town Hall */}
      <RigidBody
        type="fixed"
        colliders={false}
        position={[18, -1.3, 74]}
        rotation={[0, -1.006, 0]}
        scale={[1, 1.157, 1.123]}
      >
        <CuboidCollider args={[1, 7, 1]} />
      </RigidBody>

      {/* Green tree near the well */}
      <RigidBody type="fixed" colliders={false} position={[-42, -0.15, 22]}>
        <CuboidCollider args={[1, 10, 1]} />
      </RigidBody>

      {/* Green tree on the left from the trampoline */}
      <RigidBody
        type="fixed"
        colliders={false}
        position={[20, -0.314, -28]}
        rotation={[0, -0.375, 0]}
      >
        <CuboidCollider args={[1, 7, 1]} />
      </RigidBody>

      {/* Green tree near the Great Inscription */}
      <RigidBody
        type="fixed"
        colliders={false}
        position={[-27, -1.3, -23]}
        rotation={[-Math.PI, 0.525, -Math.PI]}
        scale={[0.92, 0.956, 1.123]}
      >
        <CuboidCollider args={[1, 7, 1]} />
      </RigidBody>

      {/* Sliced meat store near brown vases */}
      <RigidBody
        type="fixed"
        colliders={false}
        position={[-11, -0.202, 38]}
        rotation={[3.138, -0.302, -3.14]}
      >
        <CuboidCollider args={[3, 5, 1.5]} />
      </RigidBody>

      {/* Town Hall */}
      <RigidBody
        type="fixed"
        colliders={false}
        position={[25, -0.24, 54]}
        rotation={[3.136, 0.818, -3.139]}
      >
        <CuboidCollider args={[5.5, 12, 3.5]} position={[-0.5, 0, -0.25]} />
        <CuboidCollider
          args={[5, 0.1, 1.3]}
          position={[-0.4, 4.5, 5]}
          rotation={[0.3, 0, 0]}
        />
      </RigidBody>

      {/* Windmill */}
      <RigidBody type="fixed" colliders={false} position={[-110.5, 31.25, 13]}>
        <CuboidCollider args={[5, 11.75, 5]} />
        <CuboidCollider position={[0, -5, 6.5]} args={[3, 5.5, 4]} />
        <CuboidCollider position={[7, 12, 1]} args={[0.5, 5.75, 1.35]} />
        <CuboidCollider
          position={[7.8, 6.25, -7.7]}
          rotation={[Math.PI / 2, 0, 0]}
          args={[0.5, 6, 1.35]}
        />
        <CuboidCollider
          position={[7.8, 3.5, 6]}
          rotation={[Math.PI / 2, 0, 0]}
          args={[0.5, 6, 1.35]}
        />
      </RigidBody>
    </group>
  );
};

useGLTF.preload("/village.glb");
