/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Tadewaart (https://sketchfab.com/Tadewaart)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/stump-chum-2ac50e93a2ea44f48883a86694fbf905
Title: Stump Chum
*/

import { useGLTF } from "@react-three/drei";
import React, { useRef, useMemo, useEffect, type FC } from "react";
import * as THREE from "three";
import {
  useSharedStumpChumResources,
  createOptimizedStumpChumClone,
} from "~/components/three/shared-stump-chum";

interface StumpChumProps {
  hatModelPath?: string;
  hatConfig?: {
    position: [number, number, number];
    rotation: [number, number, number];
    scale: [number, number, number];
  };
  movementSpeed?: number;
  [key: string]: any;
}
export const StumpChum: FC<StumpChumProps> = ({
  hatModelPath,
  hatConfig,
  ...props
}) => {
  const group = useRef<THREE.Group>(null);
  const { scene, materials } = useSharedStumpChumResources();

  const hatScene = hatModelPath ? useGLTF(hatModelPath).scene : null;
  const hatRef = useRef<THREE.Group>(null);

  // Create optimized clone with shared materials
  const clone = useMemo(() => {
    if (!scene || !materials) return null;
    return createOptimizedStumpChumClone(scene, materials);
  }, [scene, materials]);

  useEffect(() => {
    if (!hatRef.current || !hatConfig) return;

    hatRef.current.position.set(...(hatConfig.position ?? [0, 0, 0]));
    hatRef.current.rotation.set(...(hatConfig.rotation ?? [0, 0, 0]));
    hatRef.current.scale.set(...(hatConfig.scale ?? [1, 1, 1]));
  }, [hatConfig]);

  // Proper cleanup on unmount
  useEffect(() => {
    return () => {
      // Only dispose materials that aren't shared, geometry is shared so DON'T dispose
      group.current?.traverse((obj: any) => {
        if (!obj.isMesh) return;

        // Geometry is shared - do NOT dispose it!
        // Materials might be shared too, but dispose if not in shared set
        if (Array.isArray(obj.material)) {
          obj.material.forEach((mat: THREE.Material) => {
            if (!materials.includes(mat)) {
              mat.dispose();
            }
          });
        } else if (obj.material && !materials.includes(obj.material)) {
          obj.material.dispose();
        }
      });
    };
  }, [materials]);

  if (!clone) return null;

  return (
    <group ref={group} {...props} dispose={null}>
      <primitive object={clone} scale={0.00825} />

      {hatScene && (
        <group ref={hatRef}>
          <primitive object={hatScene.clone()} />
        </group>
      )}
    </group>
  );
};
